swagger: "2.0"
info:
  description: |
    {{ description }}
  version: "{{ version }}"
  title: {{ title }}
  {% if contact %}
  contact:
    name: {{ contact }}
  {% endif %}
basePath: {{ base_path }}
schemes:
{% for scheme in schemes %}
  - {{ scheme }}
{% endfor %}
{% if security_definitions %}
securityDefinitions:
{{ security_definitions|nesteddict2yaml }}
{% endif %}
{% if definitions %}
{{ definitions }}
{% endif %}
paths:
